### ISSUE TITLE
Add License Information

### ISSUE THREAD

**Issue by thenanobel** [RabiRoshan/snake_game#2]
Add license information for this software.

As long as there is [no license](https://www.gnu.org/licenses/license-list.html#NoLicense), it can't be considered as a [free software](https://www.gnu.org/philosophy/free-sw.html).

Thanks.

**Comment by lucasliu0910** [comment]
This is a good question!

**Comment by RabiRoshan** [comment]
@thenanobel Thank You for the info. Done 😊
